apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: the-pipeline-run
spec:
  serviceAccountName: backend-frontend-sa
  pipelineRef:
    name: the-pipeline
  workspaces:
    - name: maven-settings
      emptyDir: {}
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: maven-source-pvc
  resources:
    - name: backend-docker-image
      resourceRef:
        name: backend-image-resource
    - name: frontend-docker-image
      resourceRef:
        name: frontend-image-resource
