apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-2-deployment
  namespace: demo-2
  labels:
    name: demo-2
spec:
  selector:
    matchLabels:
      app: demo-2
  template:
    metadata:
      name: demo-2
      labels:
        app: demo-2
    spec:
      containers:
        - image: "gcr.io/jovica-gcp/demo-2:latest"
          imagePullPolicy: Always
          name: demo-2
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-2-service
  namespace: demo-2
  labels:
    app: demo-2
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: demo-2
  selector:
    app: demo-2
  sessionAffinity: None
